package kagg886.youmucloud.util;

public class MusicFactory {
	public static String spawnMusic(String musicType,String name,String author,String picCover,String musicCover,String jumpUrl) {
		return "{\r\n"
				+ "	\"app\": \"com.tencent.structmsg\",\r\n"
				+ "	\"desc\": \"音乐\",\r\n"
				+ "	\"view\": \"music\",\r\n"
				+ "	\"ver\": \"0.0.0.1\",\r\n"
				+ "	\"prompt\": \"[分享]" + name + "\",\r\n"
				+ "	\"appID\": \"\",\r\n"
				+ "	\"sourceName\": \"\",\r\n"
				+ "	\"actionData\": \"\",\r\n"
				+ "	\"actionData_A\": \"\",\r\n"
				+ "	\"sourceUrl\": \"\",\r\n"
				+ "	\"meta\": {\r\n"
				+ "		\"music\": {\r\n"
				+ "			\"action\": \"\",\r\n"
				+ "			\"android_pkg_name\": \"\",\r\n"
				+ "			\"app_type\": 1,\r\n"
				+ "			\"appid\": 100497308,\r\n"
				+ "			\"desc\": \"" + author + "\",\r\n"
				+ "			\"jumpUrl\": \"" + jumpUrl + "\",\r\n"
				+ "			\"musicUrl\": \"" + musicCover + "\",\r\n"
				+ "			\"preview\": \"" + picCover + "\",\r\n"
				+ "			\"sourceMsgId\": \"0\",\r\n"
				+ "			\"source_icon\": \"\",\r\n"
				+ "			\"source_url\": \"\",\r\n"
				+ "			\"tag\": \"" + musicType + "\",\r\n"
				+ "			\"title\": \"" + name + "\"\r\n"
				+ "		}\r\n"
				+ "	},\r\n"
				+ "	\"config\": {\r\n"
				+ "		\"autosize\": true,\r\n"
				+ "		\"ctime\": 1637386732,\r\n"
				+ "		\"forward\": true,\r\n"
				+ "		\"token\": \"f47d9aed8c6ea17e93830a6a80288ac7\",\r\n"
				+ "		\"type\": \"normal\"\r\n"
				+ "	},\r\n"
				+ "	\"text\": \"\",\r\n"
				+ "	\"sourceAd\": \"\",\r\n"
				+ "	\"extra\": \"{\\\"app_type\\\":1,\\\"appid\\\":100497308,\\\"msg_seq\\\":6919845034150331024,\\\"uin\\\":1914776142}\"\r\n"
				+ "}";
	}
}
